<?php

namespace App\Http\Requests\Front;

use App\Http\Requests\BaseFormRequest;
use Illuminate\Foundation\Http\FormRequest;

class FormsRequest extends FormRequest
{
    public $formTypes = [
        'individual_bonus',
    ];

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' => 'required|string',
            'phone' => 'required|string|max:20',
            'description' => 'required',
        ];
    }

    public function messages()
    {
        return [
            'required' => 'Это поле обязательно для заполнения',
            'email' => 'Поле :attribute должно быть действительным электронным адресом.',
        ]; // TODO: Change the autogenerated stub
    }
}
